# Generated by Django 4.0.3 on 2022-04-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_rename_name_album_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
