# Generated by Django 4.0.3 on 2022-03-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0004_alter_album_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='album_name',
        ),
    ]
